-- MySQL Script generated by MySQL Workbench
-- Dom 17 Ago 2014 20:00:37 BRT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema asking
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `asking` ;
CREATE SCHEMA IF NOT EXISTS `asking` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `asking` ;

-- -----------------------------------------------------
-- Table `asking`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asking`.`user` ;

CREATE TABLE IF NOT EXISTS `asking`.`user` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `active` TINYINT(1) UNSIGNED NULL DEFAULT '1',
  `token` VARCHAR(80) NULL DEFAULT NULL,
  `change` DATETIME NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `email_password_INDEX` (`email` ASC, `password` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3;


-- -----------------------------------------------------
-- Table `asking`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asking`.`question` ;

CREATE TABLE IF NOT EXISTS `asking`.`question` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `title` VARCHAR(80) NOT NULL,
  `content` VARCHAR(300) NOT NULL,
  `closed` TINYINT(1) NULL DEFAULT 0,
  `answers` INT NULL DEFAULT 0,
  `viewed` INT NULL DEFAULT 0,
  `created` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_question_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_question_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `asking`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asking`.`answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asking`.`answer` ;

CREATE TABLE IF NOT EXISTS `asking`.`answer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `question_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `better` TINYINT(1) UNSIGNED NULL DEFAULT 0,
  `votes` INT NULL DEFAULT 0,
  `content` VARCHAR(300) NULL,
  `created` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_answer_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_answer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `asking`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asking`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asking`.`category` ;

CREATE TABLE IF NOT EXISTS `asking`.`category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `description` VARCHAR(140) NOT NULL,
  `slug` VARCHAR(60) NOT NULL,
  `created` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asking`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asking`.`tag` ;

CREATE TABLE IF NOT EXISTS `asking`.`tag` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `description` VARCHAR(140) NOT NULL,
  `slug` VARCHAR(60) NOT NULL,
  `created` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asking`.`question_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asking`.`question_category` ;

CREATE TABLE IF NOT EXISTS `asking`.`question_category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question_id` INT UNSIGNED NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_question_category_question1_idx` (`question_id` ASC),
  INDEX `fk_question_category_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_question_category_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `asking`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `asking`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asking`.`question_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asking`.`question_tag` ;

CREATE TABLE IF NOT EXISTS `asking`.`question_tag` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question_id` INT UNSIGNED NOT NULL,
  `tag_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_question_tag_tag1_idx` (`tag_id` ASC),
  INDEX `fk_question_tag_question1_idx` (`question_id` ASC),
  CONSTRAINT `fk_question_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `asking`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_tag_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `asking`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asking`.`user_meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asking`.`user_meta` ;

CREATE TABLE IF NOT EXISTS `asking`.`user_meta` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `about` VARCHAR(300) NULL,
  `viewed` INT UNSIGNED NULL DEFAULT 0,
  `answers` INT UNSIGNED NULL DEFAULT 0,
  `questions` INT UNSIGNED NULL DEFAULT 0,
  `score` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_user_meta_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_meta_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `asking`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asking`.`question_answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asking`.`question_answer` ;

CREATE TABLE IF NOT EXISTS `asking`.`question_answer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question_id` INT UNSIGNED NOT NULL,
  `answer_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_question_answer_answer1_idx` (`answer_id` ASC),
  INDEX `fk_question_answer_question1_idx` (`question_id` ASC),
  CONSTRAINT `fk_question_answer_answer1`
    FOREIGN KEY (`answer_id`)
    REFERENCES `asking`.`answer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_answer_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `asking`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
